name: Run Python
on:
    push:
jobs:
    build:
        name: set and run
        runs-on: ubuntu-last
        steps:
            - uses: actions/checkout@v2
            - name: steps1
              run: 
                python3 main.py
